# Generated by Django 3.0.2 on 2020-01-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
